site_name: bespoken.io
repo_url: https://github.com/bespoken/bst
site_dir: 'site'
strict: true
google_analytics: ['UA-99287066-2', 'docs.bespoken.io']
pages:
- Home: index.md
- Getting Started: getting_started.md
- Alexa Skill Configuration: alexa_skills_kit_configuration.md
- Commands:
    - bst proxy: commands/proxy.md
    - bst launch: commands/launch.md
    - bst intend: commands/intend.md
    - bst utter: commands/utter.md
    - bst speak: commands/speak.md
    - bst deploy: commands/deploy.md
- API Reference: api_nav.md
- Tutorials for Alexa Skills:
    - Node.js Lambda: tutorials/tutorial_lambda_nodejs.md
    - Local Java Server: tutorials/tutorial_local_server_java.md
    - Python & Flask-Ask: tutorials/tutorial_flask_ask_python.md
    - Unit-Testing Alexa: tutorials/tutorial_alexa_unit_testing.md
    - BST Alexa Emulator (OLD): tutorials/tutorial_bst_emulator_nodejs.md
- Tutorials for Actions on Google:
    - With Cloud Functions: tutorials/tutorial_cloud_function.md
    - With API.AI: tutorials/tutorial_configuring_api_ai.md
- Tutorials for General Lambdas:
    - Running Lambdas Locally: tutorials/tutorial_lambda_local.md
    - Debugging Lambdas Locally: tutorials/tutorial_lambda_debugger.md
    - Deploying Lambdas: tutorials/tutorial_lambda_deploy.md

theme: readthedocs
markdown_extensions:
- attr_list
extra_css: [assets/css/style.css]
